### ISSUE TITLE
Pager events

### ISSUE THREAD

**Issue by vladoros** [akveo/ng2-smart-table#24]
I've noticed the pager doesn't have attached any events. It would be great to add custom events on page change.

**Comment by Sravanti94** [comment]
hey @vladoros have you got any solution on this.

**Comment by AtifJaved1** [comment]
@vladoros, you can use the Angular Material Tables instead of this. as I have faced the same issue and didnt found any other solution

**Comment by Et3rnal** [comment]
I'm facing the same here, any solution to attach event anyone?

**Comment by Et3rnal** [comment]
Here is what I did if you need more specific logic it should be easy to create:
`
@HostListener('body:click', ['$event'])
onMouseclick(event: any) {    
  //console.log(event.target);
  if( (event.target && event.target.attributes.class && event.target.attributes['class'].value=="ng2-smart-page-link page-link")
  || (event.target.parentElement && event.target.parentElement.attributes['class'] && event.target.parentElement.attributes['class'].nodeValue.indexOf("ng2-smart-page-link page-link") >= 0) ){
    
    //Do something
    alert("Pager clicked");
    
  }
}`
Since there is no event, we are listening to all clicks! and pick the one we want using the class where the user clicked. yes it is not the best way.

**Comment by AkhilNaidu09** [comment]
@Et3rnal good one. But pagination steps are populated on basis of **source** length, If we create server side pagination your solution wont work. To capture click event it was a good idea 👍

**Comment by minhtam-nguyennhat** [comment]
hi, you could use the particular observable property in the data source to determine if page change occurs.

```
let data: LocalDataSource = new LocalDataSource();

this.data.onChanged().subscribe(change => {
	switch (change.action) {
		case 'page':
			this.handleSmartTablePageChange(change);
			break;
		case 'sort':
			this.handleSmartTableSort(change);
			break;
	}
});
```

Best regards
