### ISSUE TITLE
ng-template error on angular 2.x

### ISSUE THREAD

**Issue by ManpreetSingh80** [akveo/ng2-smart-table#266]
On adding latest version to a angular 2.x project, it is giving following error - 

> Template parse errors:
ng-template' is not a known element:

**Comment by LexZhukov** [comment]
@ManpreetSingh80 ng2-smart-table v1.0.0 is not compatible with angular 2. You can use v0.6.0-1.

**Comment by ManpreetSingh80** [comment]
@LexZhukov Thanks for the quick update.

**Comment by jboothe** [comment]
I can't help to point out the irony of a component named **ng2**-smart-table not being compatible with Angular 2. I would suggest documentation for those that actually want to use your component with Angular 2.

**Comment by danaERadwin** [comment]
I am using Angular 4 and installed "ng2-smart-table": "^1.0.2".
And I still receive:

> 'ng-template' is not a known element

**Comment by fopnet** [comment]
lexzhukov,  I change to v0.6.0-1 version and i still receive the same error using angular 2

**Comment by Mochoa92** [comment]
@lexzhukov how can i update my ng2-smart-table

**Comment by carmelolg** [comment]
Okay, I'm using angular 2.4.9, and I don't understand why I can't use the newest version of this component. I have to use for all software-life-long the v0.6.0-1. 
Is possible make this components compatible also for project that can't use angular 4?
Otherwise will become mandatory update angular, also in projects with mandatory version of angular.

**Comment by kruzalmighty** [comment]
Visit [https://www.versioneye.com/nodejs/ng2-smart-table/0.6.0-1](https://www.versioneye.com/nodejs/ng2-smart-table/0.6.0-1) to update
