### ISSUE TITLE
change style deployement as external file for better flexibility

### ISSUE THREAD

**Issue by amineparis** [akveo/ng2-smart-table#290]
users can't erase default style of ng2-smart-table, making it external to be included in choice enable users to define their own table style

**Comment by ameagol** [comment]
This is quite simple, as Angular2 Style Documentation says.

Override the style by adding on component.ts

```
@Component({
selector: 'app-root',
  templateUrl: './app.component.html', 
  **styleUrls:  ['./app.component.css']**
})
```
 
Then add configuration adjustments on **app.component.css**

```
:host /deep/ ng2-smart-table tbody > tr > td:first-child { 
	text-align: left; 
        background-color:red;  
}
```

**Comment by ktriek** [comment]
@ameagol thanks for this solution but this doesn't really solve a problem, someone who is using something like bootstrap should be able to style the `ng2-smart-table` just by adding css classes like `table-stripped` without overriding that css or even including it.
Also I don't think anyone would like to have  a `font-family` or `font-color` in the grid different than the rest of the application(is there any reason to have this in `ng2-smart-table.component.scss`).

**Comment by vlapo** [comment]
I don't understand. why ng2-smart-table have ```ng2-smart-table.component.scss``` ? 
Yeah I see it is some default css style but (as @ktriek  say) it is unnecessary because everybody want to style tables as the rest of application using own classes.

In my case. I migrate from angularjs to angular 2 and after use ng2-smart-table I have totally different tables because of this default style.

Examples:
 - using rem in ```font-size``` https://github.com/akveo/ng2-smart-table/issues/312, https://github.com/akveo/ng2-smart-table/issues/112 - bootstrap have 10px root font-size so fonts are tiny 
 - ```font-colors``` - I have defined my colors for tables. After applying my classes to ng2-smart-table table I have to rewrite my styles to overwrite defaults.
 - same ```font-family```

Maybe I am wrong and don't see the purpose of this scss file. Please kick me if I am wrong :)
There was a PR https://github.com/akveo/ng2-smart-table/pull/206

**Comment by vlapo** [comment]
@lexzhukov thnx a lot ;)

**Comment by RikiMizusaki** [comment]
@lexzhukov Thank you.

**Comment by amineparis** [comment]
@lexzhukov  So respectful, TY
