### ISSUE TITLE
[Question] Purpose of moving from WebPack 2 to Gulp

### ISSUE THREAD

**Issue by Deilan** [akveo/ng2-smart-table#292]
Hey guys, according to the latest updates you removed WebPack in favor of Gulp. I wonder what are the purposes of that movement?

**Comment by nnixaa** [comment]
Hey @Deilan, the main purpose is to move to angular-cli instead of having custom build (which is highly complicated to maintain).

But, answering your question, we haven't particularly moved _from_ webpack or _to_ gupl. Webpack is still there but hidden behind angular-cli. And gulp is only used to simplify the packaging process on our side.

Hope this helps ! :)

**Comment by Deilan** [comment]
@nnixaa Thank you very much for the thorough explanation, it's very appreciated! As far as I can see `Ng2SmartTableComponent` should be imported from `'ng2-smart-table/ng2-smart-table.component'` as a result of the explained approach.
