### ISSUE TITLE
Pager in ng2-smart-table

### ISSUE THREAD

**Issue by milena991** [akveo/ng2-smart-table#343]
Hi, I have problem with pager in smart table - it is vertical. How can I fix it to be horizontal? How can I change css style for smart table?

**Comment by ayualdilasalma** [comment]
@milena991 I'm facing the same problem with you. Have you found the solution for this?

**Comment by milena991** [comment]
Nothing yet... Have you ever used npm link for editing npm_modules?

**Comment by ayualdilasalma** [comment]
@milena991 no, I never used npm link..

**Comment by ssssaaamm** [comment]
I think the problem will be solved changing the  pager.component.scss to:

.ng2-smart-pagination {
  display: inline-flex;
  font-size: .875em;
  padding: 0;

  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
  }

  .ng2-smart-page-item {
    display: inline;
  }
}

instead of 

.ng2-smart-pagination {
  display: inline-block;
  font-size: .875em;
  padding: 0;

  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
  }

  .ng2-smart-page-item {
    display: inline;
  }
}

in my project  i have that file in node_modules/ng2-smart-table/components/pager/pager.component.scss.
I make this changes but it does not work, Does not work because even when the file is modified in the browser it is loaded as if it were not.
