### ISSUE TITLE
Issues regarding the ng2-smart-table (not data found)

### ISSUE THREAD

**Issue by houdejun214** [akveo/ng2-smart-table#671]
I'm trying to use ng2-smart-table following ngx-admin template,  but I got one issue as below.

My data didn't show there when the page is load,  but it will show out after I just click any filter box then move out my cursor, the data will show there.
![jan-11-2018 21-49-41](https://user-images.githubusercontent.com/3813881/34877456-1a4903a4-f7e1-11e7-8e75-bd6cf4504b27.gif)

my  ng2-smart-table  version is 1.2.2,  my angular version is 5.1.0,  please give me some advice regarding this issue?

I just copy the code from https://github.com/akveo/ngx-admin/tree/master/src/app/pages/tables/smart-table without any change right now.

**Comment by matzrm** [comment]
Hi,

I'am this problem too. Did you find a solution?

**Comment by rajanish007** [comment]
Use LocalDataSource, Add this to app.module:
import { Ng2SmartTableModule,LocalDataSource } from 'ng2-smart-table';
Then, in your component declare :
source : LocalDataSource;
constructor(){
//add data
this.source = new LocalDataSource(this.data);
}

**Comment by houdejun214** [comment]
Thx,  I finally figure this problem as I put a wrong setting in my component  `changeDetection: ChangeDetectionStrategy.OnPush`,  use `ChangeDetectionStrategy.Default` work well for me.

**Comment by ccruza** [comment]
> Use LocalDataSource, Add this to app.module:
> import { Ng2SmartTableModule,LocalDataSource } from 'ng2-smart-table';
> Then, in your component declare :
> source : LocalDataSource;
> constructor(){
> //add data
> this.source = new LocalDataSource(this.data);
> }
> Hope this helps, worked for me !

This worked for me. Just load the "source" in the ngOnInit

**Comment by ccruza** [comment]
Hello there.

I also found that.. if You have one "render component" in your column settings and this is giving an error, the table only shows the rows that are correct (without errors). Try loading sample data and test..

Example:

![image](https://user-images.githubusercontent.com/41245212/58384178-69543080-7fa4-11e9-8c1e-2826f80f10a0.png)

I was supposed to pass value to ` instance.TooltipText` but I was passing an empty string (view the image).. then inside the toolptiptext component i was using something like `value.toString()` , obviously like there is no string the function `toString()` was failing.. so I just comment that part of the code and then it works..

Greetings

**Comment by nvmnghia** [comment]
None of the solution here works for me...

**Comment by hanesjw** [comment]
This is not the most ideal solution but so far it's working for me. Maybe it will help shed some light on to what the actual issue is. This definitely seems hacky to me but here is what I did to get it to work...

I'm using ngrx and want to utilize angular's OnPush change detection.

I have a parent component set to "changeDetection: ChangeDetectionStrategy.OnPush". Yes if I change this back to the default strategy it works, but I want to use OnPush.

My child component contains the ng2-smart-table component. This component takes in an array of objects using the @input property. This object is what is used as the [source] input for the ng2-smart-table.

If I use this @input object to iterate on any other DOM element like a ul>li it works fine. So the OnPush works, the smart-table is just not detecting any changes. I'm assuming the reason the data loads after a button click is because that triggers the angular detection to mark it as changed so it then updates it later in the cycle.

What I did was force the change detection to kick in on the ngOnChanges lifecycle hook. The component looks like this...

`
export class UserTableComponent implements OnInit, OnChanges {

@input() users: User[];
settings: any;

constructor(private cd: ChangeDetectorRef) {
}

ngOnInit() {
this.initSettings();
}

ngOnChanges(changes: SimpleChanges): void {
setTimeout(() => {
this.cd.detectChanges();
}, 0);
}
}
`

**Comment by HackPoint** [comment]
> This is not the most ideal solution but so far it's working for me. Maybe it will help shed some light on to what the actual issue is. This definitely seems hacky to me but here is what I did to get it to work...
> 
> I'm using ngrx and want to utilize angular's OnPush change detection.
> 
> I have a parent component set to "changeDetection: ChangeDetectionStrategy.OnPush". Yes if I change this back to the default strategy it works, but I want to use OnPush.
> 
> My child component contains the ng2-smart-table component. This component takes in an array of objects using the @input property. This object is what is used as the [source] input for the ng2-smart-table.
> 
> If I use this @input object to iterate on any other DOM element like a ul>li it works fine. So the OnPush works, the smart-table is just not detecting any changes. I'm assuming the reason the data loads after a button click is because that triggers the angular detection to mark it as changed so it then updates it later in the cycle.
> 
> What I did was force the change detection to kick in on the ngOnChanges lifecycle hook. The component looks like this...
> 
> `
> export class UserTableComponent implements OnInit, OnChanges {
> 
> @input() users: User[];
> settings: any;
> 
> constructor(private cd: ChangeDetectorRef) {
> }
> 
> ngOnInit() {
> this.initSettings();
> }
> 
> ngOnChanges(changes: SimpleChanges): void {
> setTimeout(() => {
> this.cd.detectChanges();
> }, 0);
> }
> }
> `
> 
> If i remove the setTimeout it doesn't work for some reason. Yes it seems hacky but it works for me. I don't know if I'm doing something wrong or if ng2-smart-table has a bug that isn't detecting changes correctly. Anyways, hope it helps.

After testing every suggestion that has been I'm still having this issue. How did you solved it?

**Comment by hanesjw** [comment]
This still doesn't seem to be working with OnPush. Does ng2-smart-table not allow an OnPush change detection? Why was this set to 'closed' with no resolution?

**Comment by vanavaraVL** [comment]
Well, actually, you can use the following in case OnPush strategy and ServerDataSource.

```
public source: DataSource;

private subscriptions: Subscription[] = [];

constructor(
    private http: HttpClient,
    private ref: ChangeDetectorRef,
  ) {
  }

ngOnInit(): void {
    this.source = new ServerDataSource(
      this.http, {});

    const subscription = this.source.onChanged()
      .pipe(tap(() => this.ref.markForCheck()))
      .subscribe();

    this.subscriptions.push(subscription);

    this.refreshDataSourceOnFormSave();
}

public ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
}
```
